apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: myreactapp
  ports:
       - port: 80
         targetPort: 5173
  type: NodePort    


# apiVersion: v1
# kind: Service

# metadata:
#   name: react-service

# spec:
#   selector:
#     app: myreactapp

#   ports:
#     - port: 80
#       targetPort: 80

#   type: NodePort