apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      labels:
        app: myreactapp
    spec:
        containers:
          - name:  myreactapp
            image:  sunny19k98/react-app:v1.20
            
