apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingresprac
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: back-svc
              port: 
                number: 80
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingressprac
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: myapp.local
#     https:
#          paths: /api
#          pathType: Prefix
#          backend:
#            service:
#              name: backend-svc
#              port:
#                number: 80
